### ISSUE TITLE
turnstile did not working

### ISSUE THREAD

**Issue by jeremiatoga123** [Theyka/turnstile-solver#2]
the turnstile always having some trouble, is it still work on you guys? or it just me?

**Comment by sexfrance** [comment]
@jeremiatoga123 Check the site key make sure you don't use the headless option if you have slow internet make the waiting time before clicking bigger, if you are using proxies make sure you don't use free ones as they might be flagged, and disable your vpn/proxy connection and check your IP address it might be flagged. Since you can see the chromium instance try checking what is wrong

@Theyka I made a pull request 3 weeks ago I figured you already checked it, if you don't want to integrate it please deny it.
